language: python

python:
  - "3.6"
  - "3.7"

# Install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --no-cache-dir -U -r requirements.txt
  - apt-get install python-opengl

# Run unit test
script:
  - pytest tests/. -v --cov=pilco --cov-report term-missing

after_success:
  - coveralls
