language: python

python:
  - "3.6"
  - "3.7"

# Install dependencies
install:
  - sudo apt-get install python-opengl
  - pip install --upgrade pip setuptools wheel
  - pip install --no-cache-dir -U -r requirements.txt

# Run unit test
script:
  - pytest tests/. -v --cov=pilco --cov-report term-missing

after_success:
  - coveralls
